<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Material3" Version="$(Material3Version)" />
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <ProjectReference Include="../Gallery/Gallery.csproj" />
  </ItemGroup>
</Project>
